//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H_Gates_Managment__System
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HGatesDesktopAppEntities2 : DbContext
    {
        public HGatesDesktopAppEntities2()
            : base("name=HGatesDesktopAppEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Condition> Conditions { get; set; }
        public virtual DbSet<Doctor> Doctors { get; set; }
        public virtual DbSet<EmergencyRelationship> EmergencyRelationships { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<Intake> Intakes { get; set; }
        public virtual DbSet<Nurse> Nurses { get; set; }
        public virtual DbSet<Parish> Parishes { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<Procedure> Procedures { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<Specialization> Specializations { get; set; }
        public virtual DbSet<Administrator> Administrators { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<User> Users { get; set; }
    
        public virtual ObjectResult<GetPatientsList_Result> GetPatientsList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPatientsList_Result>("GetPatientsList");
        }
    
        public virtual ObjectResult<GetAllPatients_Result> GetAllPatients()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllPatients_Result>("GetAllPatients");
        }
    }
}
