//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H_Gates_Managment__System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Intake
    {
        public int Id { get; set; }
        public Nullable<int> PatientID { get; set; }
        public System.DateTime IntakeDate { get; set; }
        public Nullable<int> ConditionID { get; set; }
        public Nullable<int> ProcedureID { get; set; }
        public Nullable<int> DoctorID { get; set; }
        public Nullable<int> RoomID { get; set; }
    
        public virtual Condition Condition { get; set; }
        public virtual Doctor Doctor { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual Procedure Procedure { get; set; }
        public virtual Room Room { get; set; }
    }
}
