//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H_Gates_Managment__System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patient()
        {
            this.Intakes = new HashSet<Intake>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public Nullable<int> GenderID { get; set; }
        public string StreetAddress { get; set; }
        public string City { get; set; }
        public Nullable<int> ParishID { get; set; }
        public string ContactName { get; set; }
        public string EContactNo { get; set; }
        public string ContactAddress { get; set; }
        public Nullable<int> ERelationshipID { get; set; }
    
        public virtual EmergencyRelationship EmergencyRelationship { get; set; }
        public virtual Gender Gender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Intake> Intakes { get; set; }
        public virtual Parish Parish { get; set; }
    }
}
